name: api_happiness
description: Shared Dart API for project Happiness.
version: 0.1.0+100
publish_to: none

environment:
  sdk: '>=2.17.3 <3.0.0'


dependencies:
  dart_helpers:
    path: ../../dart_helpers
    #git: https://github.com/signmotion/dart_helpers

  equatable: ^2.0.3


dev_dependencies:
  build_runner: ^2.1.11
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  lints: ^2.0.0
